name: Release Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build the Docker image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 -t ericjin07/siyuan:latest -t ericjin07/siyuan:v3.0.8 .
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VPS and execute script
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/eric/docker-env
            docker compose down
            sed -i 's/\(IMG_SIYUAN=.*:\)v[0-9.]\+/\1v3.0.8/' .env
            docker compose up -d
      

